workspace:
  base: /go
  path: src/github.com/maksmiles/smart-logic

pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go test
      - go build -o application
